name: Generate Changelog

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_GITHUB_PAT }}

      - name: Check if last commit is a changelog commit
        id: skip_check
        run: |
          MSG=$(git log -1 --pretty=%B | tr '[:upper:]' '[:lower:]')
          echo "Last commit message: $MSG"
          if echo "$MSG" | grep -q "skip-changelog"; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip workflow if last commit is changelog
        if: steps.skip_check.outputs.skip == 'true'
        run: |
          echo "Skipping workflow because last commit is [skip-changelog]"
          exit 0

      - name: Run changelog generator script
        run: |
          chmod +x ./scripts/changelogs-generator.sh
          ./scripts/changelogs-generator.sh

      - name: Commit & Push Changelog
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          echo "Checking for changes in CHANGELOG.md"
          git status
          git diff CHANGELOG.md || true

          if git diff --quiet CHANGELOG.md; then
            echo "No changes in CHANGELOG.md. Skipping commit."
            exit 0
          fi

          git add CHANGELOG.md
          git commit -m "chore: update changelog [skip-changelog]"

          echo "Pushing changes to main"
          git push origin main

      - name: Show last changelog changes
        run: |
          echo "Last 10 lines of CHANGELOG.md:"
          tail -n 10 CHANGELOG.md
