name: Generate Changelog

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # penting agar git log lengkap

      - name: Check if last commit is a changelog commit
        id: skip_check
        run: |
          MSG=$(git log -1 --pretty=%B | tr '[:upper:]' '[:lower:]')
          if echo "$MSG" | grep -q "skip-changelog"; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip workflow if changelog commit
        if: steps.skip_check.outputs.skip == 'true'
        run: |
          echo "Skipping because commit is marked [skip-changelog]"
          exit 0

      - name: Run changelog generator script
        run: |
          chmod +x ./scripts/changelogs-generator.sh
          ./scripts/changelogs-generator.sh

      - name: Commit & Push Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Gitea Actions"
          git config user.email "actions@gitea.local"

          # only commit if changelog changed
          if git diff --quiet CHANGELOG.md; then
            echo "No changes in CHANGELOG.md. Skipping commit."
            exit 0
          fi

          git add CHANGELOG.md
          git commit -m "chore: update changelog [skip-changelog]"

          # gunakan token untuk push
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
